// All built-in puzzles. Grid legend is in src/core/puzzle.ts.
// tests/levels.test.ts proves every one of these can be finished, so feel free
// to add or tweak levels -- `npm test` will tell you if one breaks.

import type { Kind } from '../core/types.ts';

export type TreatKind = 'berry' | 'star' | 'carrot' | 'cupcake' | 'apple' | 'candy' | 'cookie';

export interface Level {
  id: string;
  grid: readonly string[];
}

export interface World {
  id: string;
  /** Friends shown on the world's bubble. */
  faces: readonly Kind[];
  treat: TreatKind;
  /** Background tint for this world's screens. */
  sky: string;
  /** Grown-up explanation, shown only in the grown-up panel. */
  lesson: string;
  levels: readonly Level[];
}

function world(def: Omit<World, 'levels'> & { grids: readonly (readonly string[])[] }): World {
  const { grids, ...rest } = def;
  return { ...rest, levels: grids.map((grid, i) => ({ id: `${def.id}-${i + 1}`, grid })) };
}

export const WORLDS: readonly World[] = [
  world({
    id: 'king',
    faces: ['king'],
    treat: 'berry',
    sky: '#fef3c7',
    lesson: 'The King takes one step in any direction, including diagonals.',
    grids: [
      ['.*.',
       '.K.',
       '...'],
      ['..*',
       '.K.',
       '...'],
      ['*...',
       '.*..',
       '..*.',
       '...K'],
      ['*...',
       '....',
       '.K..',
       '...*'],
      ['.....',
       '.***.',
       '.*K*.',
       '.***.',
       '.....'],
      ['..*..',
       '.###.',
       '..K..',
       '.....',
       '.....'],
      ['.....',
       '*#.#*',
       '..K..',
       '.#.#.',
       '.....'],
    ],
  }),

  world({
    id: 'rook',
    faces: ['rook'],
    treat: 'star',
    sky: '#dbeafe',
    lesson: 'The Rook slides any distance in a straight line: up, down, left or right. Rocks and treats stop it.',
    grids: [
      ['*...',
       '....',
       '....',
       'R...'],
      ['....',
       '....',
       'R..*',
       '....'],
      ['*..*',
       '....',
       '....',
       'R...'],
      ['.....',
       '..*..',
       '.....',
       '..#..',
       '..R..'],
      ['R.*.*',
       '.....',
       '.....',
       '.....',
       '*....'],
      ['*...*',
       '.....',
       '..R..',
       '.....',
       '*...*'],
      ['*...#',
       '.##..',
       '.#*#.',
       '.#.#.',
       'R#..*'],
    ],
  }),

  world({
    id: 'bishop',
    faces: ['bishop'],
    treat: 'candy',
    sky: '#ede9fe',
    lesson: 'The Bishop slides any distance diagonally. It always stays on squares of the same color.',
    grids: [
      ['...*',
       '....',
       '.B..',
       '....'],
      ['*...',
       '....',
       '..B.',
       '....'],
      ['*...*',
       '.....',
       '..B..',
       '.....',
       '.....'],
      ['*...*',
       '.....',
       '..B..',
       '.....',
       '*...*'],
      ['*.*..',
       '.....',
       '#.B.#',
       '.....',
       '..*.*'],
      ['....*',
       '.#...',
       '*.B..',
       '...#.',
       '..*..'],
    ],
  }),

  world({
    id: 'queen',
    faces: ['queen'],
    treat: 'cupcake',
    sky: '#fce7f3',
    lesson: 'The Queen slides any distance in any direction: straight like a Rook or diagonal like a Bishop.',
    grids: [
      ['*...',
       '....',
       '....',
       '...Q'],
      ['*..*',
       '....',
       '....',
       'Q...'],
      ['*.*.*',
       '.....',
       '*.Q.*',
       '.....',
       '*.*.*'],
      ['..*..',
       '.....',
       '*.#.*',
       '.#Q#.',
       '.....'],
      ['*...#.',
       '.#....',
       '...*..',
       '#..#.*',
       '.*....',
       'Q...#.'],
      ['.*.*.',
       '*...*',
       '..Q..',
       '*...*',
       '.*.*.'],
    ],
  }),

  world({
    id: 'knight',
    faces: ['knight'],
    treat: 'carrot',
    sky: '#ffedd5',
    lesson: 'The Knight jumps in an L: two squares one way, then one square to the side. It is the only piece that jumps over things.',
    grids: [
      ['....',
       '.*..',
       '....',
       '..N.'],
      ['....',
       '....',
       '*...',
       '..N.'],
      ['.....',
       '.*...',
       '.###.',
       '.#N#.',
       '.###.'],
      ['*....',
       '.....',
       '.*...',
       '.....',
       '..N..'],
      ['.*.*.',
       '.....',
       '..N..',
       '.....',
       '.*.*.'],
      ['*...*',
       '#####',
       '.....',
       '#####',
       '..N..'],
      ['..*...',
       '.####.',
       '.#..#.',
       '.#N.#.',
       '.####.',
       '...*..'],
    ],
  }),

  world({
    id: 'pawn',
    faces: ['pawn'],
    treat: 'apple',
    sky: '#dcfce7',
    lesson: 'The Pawn steps straight up one square, but can only eat diagonally. Something right in front of it blocks it. When it reaches the far side it becomes a Queen!',
    grids: [
      ['.*..',
       '....',
       '..P.',
       '....'],
      ['....',
       '....',
       '...*',
       '..P.'],
      ['*...',
       '.*..',
       '..*.',
       '...P'],
      ['.*..',
       '.*..',
       '*...',
       '.P..'],
      ['....*',
       '.....',
       '*....',
       '.....',
       '..P..'],
      ['*...*',
       '.....',
       '..*..',
       '.*...',
       '..P..'],
    ],
  }),

  world({
    id: 'friends',
    faces: ['rook', 'bishop'],
    treat: 'cookie',
    sky: '#e0f2fe',
    lesson: 'Two friends at once. Tap a friend to choose who moves. Friends block each other, so sometimes one has to step aside.',
    grids: [
      ['*...*',
       '.....',
       '.....',
       '.....',
       'R...B'],
      ['..*..',
       '.....',
       'N...K',
       '.....',
       '*....'],
      ['*...*',
       '.....',
       '..*..',
       '.....',
       'RB...'],
      ['*.*.*',
       '.....',
       '.....',
       '.....',
       'QN...'],
      ['..*..',
       '.*.*.',
       '.....',
       '.#.#.',
       'R.P.B'],
      ['*....*',
       '......',
       '..##..',
       '..#...',
       '......',
       'NR..*.'],
    ],
  }),
];

export function findLevel(levelId: string): { world: World; index: number } | null {
  for (const w of WORLDS) {
    const index = w.levels.findIndex((l) => l.id === levelId);
    if (index >= 0) return { world: w, index };
  }
  return null;
}
