import { Level } from './types';

export const levels: Level[] = [
  {
    id: 1,
    name: 'The Royal Path',
    description: 'The Queen can move any way she likes!',
    pieceType: 'queen',
    start: { row: 4, col: 0 },
    goal: { row: 0, col: 4 },
    obstacles: {
      fences: [],
      rivers: [],
      bridges: [],
    },
    starThresholds: { three: 1, two: 2 },
    hint: 'A Queen can move like a Rook or a Bishop. Go straight there in one diagonal slide!',
  },
  {
    id: 2,
    name: 'The Crown’s Detour',
    description: 'A long fence blocks the direct diagonal. Use your Rook moves!',
    pieceType: 'queen',
    start: { row: 4, col: 4 },
    goal: { row: 0, col: 0 },
    obstacles: {
      fences: [
        { row: 2, col: 2, side: 'top' },
        { row: 1, col: 1, side: 'right' },
      ],
      rivers: [],
      bridges: [],
    },
    starThresholds: { three: 2, two: 3 },
    hint: 'If you can’t slide diagonally through the fence, try moving straight up and then left.',
  },
  {
    id: 3,
    name: 'The Queen’s Moat',
    description: 'The river is wide, but the Queen finds the gap.',
    pieceType: 'queen',
    start: { row: 4, col: 2 },
    goal: { row: 0, col: 2 },
    obstacles: {
      fences: [],
      rivers: [
        { row: 2, col: 0 },
        { row: 2, col: 1 },
        { row: 2, col: 2 }, // Blocked center
        { row: 2, col: 3 },
        { row: 2, col: 4 },
      ],
      bridges: [
        { row: 2, col: 0 }, // Bridge on far left
        { row: 2, col: 4 }, // Bridge on far right
      ],
    },
    starThresholds: { three: 3, two: 4 },
    hint: 'Use a diagonal move to reach a bridge, cross it, and slide back to the center.',
  },
  {
    id: 4,
    name: 'The Grand Slalom',
    description: 'The Queen must weave through rivers and fences.',
    pieceType: 'queen',
    start: { row: 4, col: 0 },
    goal: { row: 0, col: 4 },
    obstacles: {
      fences: [
        { row: 0, col: 2, side: 'bottom' },
      ],
      rivers: [
        { row: 2, col: 0 },
        { row: 2, col: 1 },
        { row: 2, col: 3 },
        { row: 1, col: 3 },
        { row: 1, col: 4 },
      ],
      bridges: [
        { row: 2, col: 2 },        
      ],
    },
    starThresholds: { three: 3, two: 5 },
    hint: 'Try a diagonal move to the center, then another diagonal to clear the fences.',
  },
  {
    id: 5,
    name: 'The Castle Road',
    description: 'Guide the Rook straight up to the flag!',
    pieceType: 'rook',
    start: { row: 4, col: 2 },
    goal: { row: 0, col: 2 },
    obstacles: {
      fences: [],
      rivers: [],
      bridges: [],
    },
    starThresholds: { three: 1, two: 2 },
    hint: 'The Rook moves in straight lines — up, down, left, or right.',
  },
  {
    id: 6,
    name: 'Around the Fence',
    description: 'A fence blocks the way — go around it!',
    pieceType: 'rook',
    start: { row: 4, col: 2 },
    goal: { row: 0, col: 2 },
    obstacles: {
      fences: [{ row: 2, col: 2, side: 'top' }],
      rivers: [],
      bridges: [],
    },
    starThresholds: { three: 3, two: 4 },
    hint: 'Move sideways first, then slide up, then come back toward the flag.',
  },
  {
    id: 7,
    name: 'River Crossing',
    description: 'A river blocks the path. Find the bridge!',
    pieceType: 'rook',
    start: { row: 4, col: 2 },
    goal: { row: 0, col: 2 },
    obstacles: {
      fences: [],
      rivers: [
        { row: 2, col: 0 },
        { row: 2, col: 1 },
        { row: 2, col: 2 },
        { row: 2, col: 3 },
        { row: 2, col: 4 },
      ],
      bridges: [{ row: 2, col: 4 }],
    },
    starThresholds: { three: 3, two: 4 },
    hint: 'Slide to the far-right bridge, cross the river, then slide back to the goal.',
  },
  {
    id: 8,
    name: 'Fence Garden',
    description: 'Two fences make a tiny maze for the Rook.',
    pieceType: 'rook',
    start: { row: 4, col: 0 },
    goal: { row: 0, col: 4 },
    obstacles: {
      fences: [
        { row: 0, col: 0, side: 'bottom' },
        { row: 3, col: 1, side: 'top' },
        { row: 1, col: 3, side: 'left' },
        { row: 4, col: 4, side: 'left' },
      ],
      rivers: [],
      bridges: [],
    },
    starThresholds: { three: 3, two: 4 },
    hint: 'The Rook likes long straight roads. Find the route that lines up the goal.',
  },
  {
    id: 9,
    name: 'Bridge Parade',
    description: 'A wider river has a bridge in the middle lane.',
    pieceType: 'rook',
    start: { row: 4, col: 4 },
    goal: { row: 0, col: 0 },
    obstacles: {
      fences: [],
      rivers: [
        { row: 2, col: 0 },
        { row: 2, col: 1 },
        { row: 2, col: 2 },
        { row: 2, col: 3 },
        { row: 2, col: 4 },
      ],
      bridges: [{ row: 2, col: 2 }],
    },
    starThresholds: { three: 3, two: 4 },
    hint: 'Line up with the center bridge first, then cross.',
  },
  {
    id: 10,
    name: 'Diagonal Dash',
    description: 'The Bishop slides corner to corner.',
    pieceType: 'bishop',
    start: { row: 4, col: 0 },
    goal: { row: 0, col: 4 },
    obstacles: {
      fences: [],
      rivers: [],
      bridges: [],
    },
    starThresholds: { three: 1, two: 2 },
    hint: 'Bishops only move diagonally.',
  },
  {
    id: 11,
    name: 'Zigzag Meadow',
    description: 'A pond blocks the easy diagonal path.',
    pieceType: 'bishop',
    start: { row: 4, col: 0 },
    goal: { row: 1, col: 3 },
    obstacles: {
      fences: [],
      rivers: [
        { row: 2, col: 2 },
        { row: 3, col: 3 },
      ],
      bridges: [],
    },
    starThresholds: { three: 4, two: 5 },
    hint: 'Take a smaller diagonal first, then change direction.',
  },
  {
    id: 12,
    name: 'Bridge Hop',
    description: 'The Bishop can cross the stream through the bridge.',
    pieceType: 'bishop',
    start: { row: 4, col: 0 },
    goal: { row: 0, col: 0 },
    obstacles: {
      fences: [],
      rivers: [
        { row: 2, col: 0 },
        { row: 2, col: 1 },
        { row: 2, col: 2 },
        { row: 2, col: 3 },
        { row: 2, col: 4 },
      ],
      bridges: [{ row: 2, col: 2 }],
    },
    starThresholds: { three: 4, two: 5 },
    hint: 'Aim along a diagonal that passes through the center bridge.',
  },
  {
    id: 13,
    name: 'Mirror Mountain',
    description: 'Bounce diagonally around little obstacles to the far side.',
    pieceType: 'bishop',
    start: { row: 4, col: 4 },
    goal: { row: 0, col: 0 },
    obstacles: {
      fences: [],
      rivers: [
        { row: 2, col: 3 },
        { row: 2, col: 2 },
        { row: 2, col: 1 },
        { row: 2, col: 0 },
      ],
      bridges: [
        { row: 2, col: 4 },
      ],
    },
    starThresholds: { three: 5, two: 6 },
    hint: 'If the longest diagonal is blocked, land on a different color-matching square first.',
  },
  {
    id: 14,
    name: 'The Horse Jump',
    description: 'The Knight jumps in an L-shape.',
    pieceType: 'knight',
    start: { row: 4, col: 0 },
    goal: { row: 2, col: 1 },
    obstacles: {
      fences: [],
      rivers: [],
      bridges: [],
    },
    starThresholds: { three: 1, two: 2 },
    hint: 'Two squares one way and one square sideways makes an L.',
  },
  {
    id: 15,
    name: 'Leaping the Fence',
    description: 'Fences do not stop a Knight.',
    pieceType: 'knight',
    start: { row: 4, col: 0 },
    goal: { row: 1, col: 3 },
    obstacles: {
      fences: [
        { row: 3, col: 0, side: 'top' },
        { row: 3, col: 1, side: 'top' },
        { row: 3, col: 2, side: 'top' },
        { row: 3, col: 3, side: 'top' },
        { row: 3, col: 4, side: 'top' },
      ],
      rivers: [],
      bridges: [],
    },
    starThresholds: { three: 2, two: 3 },
    hint: 'Jump over the fence line and keep aiming for the corner.',
  },
  {
    id: 16,
    name: 'River Jumper',
    description: 'Jump over the river and land safely on the other side!',
    pieceType: 'knight',
    start: { row: 4, col: 2 },
    goal: { row: 1, col: 1 },
    obstacles: {
      fences: [],
      rivers: [
        { row: 2, col: 0 },
        { row: 2, col: 1 },
        { row: 2, col: 2 },
        { row: 2, col: 3 },
        { row: 2, col: 4 },
      ],
      bridges: [],
    },
    starThresholds: { three: 2, two: 3 },
    hint: 'Knights can jump over the river row. Try landing on the top half of the board first.',
  },
  {
    id: 17,
    name: 'Bridge and Fence Picnic',
    description: 'The Knight ignores both fences and rivers while it hops.',
    pieceType: 'knight',
    start: { row: 4, col: 3 },
    goal: { row: 1, col: 0 },
    obstacles: {
      fences: [
        { row: 3, col: 2, side: 'top' },
        { row: 1, col: 1, side: 'right' },
      ],
      rivers: [
        { row: 2, col: 0 },
        { row: 2, col: 1 },
        { row: 2, col: 2 },
        { row: 2, col: 3 },
        { row: 2, col: 4 },
      ],
      bridges: [{ row: 2, col: 2 }],
    },
    starThresholds: { three: 2, two: 3 },
    hint: 'Hop to the top side, then land on the flag square in one more jump.',
  },
  {
    id: 18,
    name: 'Knight Parade',
    description: 'A longer hopping path for your final adventure.',
    pieceType: 'knight',
    start: { row: 4, col: 1 },
    goal: { row: 0, col: 0 },
    obstacles: {
      fences: [
        { row: 3, col: 1, side: 'top' },
        { row: 1, col: 3, side: 'left' },
      ],
      rivers: [
        { row: 2, col: 1 },
        { row: 2, col: 3 },
      ],
      bridges: [],
    },
    starThresholds: { three: 3, two: 4 },
    hint: 'Look for a three-jump route: the first hop is tricky, it lands FAR from the goal!',
  },
];
